# Generated by Django 5.2.7 on 2025-11-08 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_category_course_coursemodule_lesson'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='data_of_birth',
            new_name='date_of_birth',
        ),
    ]
